apiVersion: cert-manager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: raveekirann-com-tls
spec:
    secretName: raveekirann-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIsuer
    commonName: raveekirann.com
    dnsNames:
        - raveekirann.com
        - www.raveekirann.com
    acme:
        config:
            - {http01: {ingressClass: ngnix}, domains: [raveekirann.com, www.raveekirann.com]}