apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "raveekirann@yahoo.co.in"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx